// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtarioStudy.DataBaseContext;

#nullable disable

namespace OtarioLearning.Migrations
{
    [DbContext(typeof(OtarioDbContext))]
    [Migration("20240208175509_UpdatePropertyWord")]
    partial class UpdatePropertyWord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("OtarioStudy.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TodaysTopic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OtarioStudy.Models.Words", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ForeignWordsTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("OtarioStudy.Models.WordsTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BelongWordsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForeignWordsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForeignWordsId")
                        .IsUnique();

                    b.ToTable("WordsTopics");
                });

            modelBuilder.Entity("UserWordsTopic", b =>
                {
                    b.Property<int>("PassedTopicsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PassedTopicsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserWordsTopic");
                });

            modelBuilder.Entity("OtarioStudy.Models.WordsTopic", b =>
                {
                    b.HasOne("OtarioStudy.Models.Words", "Words")
                        .WithOne("WordsTopics")
                        .HasForeignKey("OtarioStudy.Models.WordsTopic", "ForeignWordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Words");
                });

            modelBuilder.Entity("UserWordsTopic", b =>
                {
                    b.HasOne("OtarioStudy.Models.WordsTopic", null)
                        .WithMany()
                        .HasForeignKey("PassedTopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtarioStudy.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OtarioStudy.Models.Words", b =>
                {
                    b.Navigation("WordsTopics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
